import fs from 'node:fs/promises';
import { atomicWrite, readIfExists } from '../files.js';
import { generatedTheme, ghosttyConfigPath, ghosttyThemePath } from '../paths.js';
import type { AppAdapter, GhosttyAppConfig, ResolvedTheme } from '../types.js';

export function generateGhostty(theme: ResolvedTheme): string {
  const terminal = [
    theme.terminal.black, theme.terminal.red, theme.terminal.green, theme.terminal.yellow,
    theme.terminal.blue, theme.terminal.magenta, theme.terminal.cyan, theme.terminal.white,
    theme.terminal.brightBlack, theme.terminal.brightRed, theme.terminal.brightGreen, theme.terminal.brightYellow,
    theme.terminal.brightBlue, theme.terminal.brightMagenta, theme.terminal.brightCyan, theme.terminal.brightWhite,
  ];
  const lines = [
    '# Generated by one-theme. Edit the canonical theme JSON, not this file.',
    `background = ${theme.ui.background}`,
    `foreground = ${theme.ui.text}`,
    `cursor-color = ${theme.ui.text}`,
    `cursor-text = ${theme.ui.background}`,
    `selection-background = ${theme.ui.selection}`,
    `selection-foreground = ${theme.ui.text}`,
  ];
  terminal.forEach((color, index) => lines.push(`palette = ${index}=${color}`));
  lines.push('');
  return lines.join('\n');
}

async function detectGhostty(): Promise<boolean> {
  try {
    await fs.access(ghosttyConfigPath());
    return true;
  } catch {
    return false;
  }
}

function parseTheme(content: string): string | null {
  const line = content.split('\n').find(item => /^\s*theme\s*=/.test(item));
  if (!line) return null;
  const current = line.replace(/^\s*theme\s*=\s*/, '').trim();
  const dark = current.match(/(?:^|,)dark:([^,]+)/);
  return (dark?.[1] ?? current).trim() || null;
}

function setGhosttyTheme(content: string, theme: string): string {
  const lines = content.split('\n');
  const themeLine = lines.findIndex(line => /^\s*theme\s*=/.test(line));
  if (themeLine === -1) {
    const prefix = content.endsWith('\n') || content.length === 0 ? content : `${content}\n`;
    return `${prefix}theme = ${theme}\n`;
  }

  const current = lines[themeLine]!.replace(/^\s*theme\s*=\s*/, '').trim();
  if (current.includes('dark:')) {
    lines[themeLine] = `theme = ${current.replace(/dark:[^,]+/, `dark:${theme}`)}`;
  } else if (current.includes('light:')) {
    lines[themeLine] = `theme = ${current},dark:${theme}`;
  } else {
    lines[themeLine] = `theme = ${theme}`;
  }
  return lines.join('\n');
}

async function currentTheme(): Promise<string | null> {
  const content = await readIfExists(ghosttyConfigPath());
  return content === null ? null : parseTheme(content);
}

async function writeTheme(theme: string): Promise<void> {
  const file = ghosttyConfigPath();
  const existing = await readIfExists(file);
  const next = setGhosttyTheme(existing ?? '', theme);
  await atomicWrite(file, next.endsWith('\n') ? next : `${next}\n`);
}

async function activateGhostty(): Promise<string | undefined> {
  await writeTheme(generatedTheme());
  return 'Ghostty may need config reload or a new window to pick up the generated theme.';
}

export const ghosttyTarget: AppAdapter<GhosttyAppConfig> = {
  name: 'ghostty',
  label: 'Ghostty',
  defaultConfig: {},
  outputPath: ghosttyThemePath,
  generate: generateGhostty,
  detect: detectGhostty,
  currentTheme,
  activate: activateGhostty,
  deactivate: async config => {
    await writeTheme(config.previousTheme ?? 'Builtin Dark');
    return 'Ghostty may need config reload or a new window to pick up the restored theme.';
  },
};
