import fs from 'node:fs/promises';
import { atomicWrite, readIfExists } from '../files.js';
import { generatedTheme, herdrConfigPath, herdrThemePath } from '../paths.js';
import { run } from '../process.js';
import type { AppAdapter, HerdrAppConfig, ResolvedTheme } from '../types.js';

const requiredColors = [
  'accent', 'panel_bg', 'surface0', 'active_space_bg', 'surface1', 'surface_dim',
  'separator', 'overlay0', 'overlay1', 'text', 'subtext0', 'mauve', 'green',
  'yellow', 'red', 'blue', 'teal', 'peach',
] as const;

function herdrBackground(theme: ResolvedTheme, config: HerdrAppConfig): string {
  return config.transparency ? 'reset' : theme.ui.background;
}

function colors(theme: ResolvedTheme, config: HerdrAppConfig): Record<(typeof requiredColors)[number], string> {
  return {
    accent: theme.ui.accent,
    panel_bg: herdrBackground(theme, config),
    surface0: theme.ui.elevated,
    active_space_bg: theme.ui.elevated,
    surface1: theme.ui.selection,
    surface_dim: theme.ui.elevated,
    separator: theme.ui.border,
    overlay0: theme.ui.textMuted,
    overlay1: theme.ui.textSubtle,
    text: theme.ui.text,
    subtext0: theme.ui.textSubtle,
    mauve: theme.ui.special,
    green: theme.ui.success,
    yellow: theme.ui.warning,
    red: theme.ui.error,
    blue: theme.ui.info,
    teal: theme.ui.hint,
    peach: theme.ui.interrupted,
  };
}

export function generateHerdr(theme: ResolvedTheme, config: HerdrAppConfig): string {
  const resolved = colors(theme, config);
  const lines = [
    '# Generated by one-theme. Edit the canonical theme JSON, not this file.',
    'schema_version = 1',
    `name = ${JSON.stringify(generatedTheme())}`,
    '',
    '[colors]',
  ];
  for (const key of requiredColors) lines.push(`${key} = ${JSON.stringify(resolved[key])}`);
  lines.push('');
  return lines.join('\n');
}

async function detectHerdr(): Promise<boolean> {
  try {
    await fs.access(herdrConfigPath());
    return true;
  } catch {
    return false;
  }
}

function themeSectionRange(lines: string[]): { start: number; end: number } | null {
  const start = lines.findIndex(line => /^\s*\[theme\]\s*$/.test(line));
  if (start === -1) return null;
  const next = lines.findIndex((line, index) => index > start && /^\s*\[[^\]]+\]\s*$/.test(line));
  return { start, end: next === -1 ? lines.length : next };
}

function parseTheme(content: string): string | null {
  const lines = content.split('\n');
  const range = themeSectionRange(lines);
  if (!range) return null;
  for (let index = range.start + 1; index < range.end; index += 1) {
    const match = lines[index]?.match(/^\s*name\s*=\s*"([^"]+)"/);
    if (match) return match[1]!;
  }
  return null;
}

function setTheme(content: string, theme: string): string {
  const lines = content.split('\n');
  const range = themeSectionRange(lines);
  if (!range) {
    const prefix = content.endsWith('\n') || content.length === 0 ? content : `${content}\n`;
    return `${prefix}[theme]\nname = ${JSON.stringify(theme)}\n`;
  }
  for (let index = range.start + 1; index < range.end; index += 1) {
    if (/^\s*name\s*=/.test(lines[index] ?? '')) {
      lines[index] = `name = ${JSON.stringify(theme)}`;
      return lines.join('\n');
    }
  }
  lines.splice(range.start + 1, 0, `name = ${JSON.stringify(theme)}`);
  return lines.join('\n');
}

async function currentTheme(): Promise<string | null> {
  const content = await readIfExists(herdrConfigPath());
  return content === null ? null : parseTheme(content);
}

async function writeTheme(theme: string): Promise<void> {
  const file = herdrConfigPath();
  const content = await readIfExists(file);
  await atomicWrite(file, setTheme(content ?? '', theme));
}

async function reloadHerdr(): Promise<string | undefined> {
  const binary = process.env.ONE_THEME_HERDR_BIN ?? 'hrd';
  let reload;
  try {
    reload = await run(binary, ['server', 'reload-config']);
  } catch {
    return 'Herdr config was updated, but live reload was skipped because hrd was not found.';
  }
  if (reload.code !== 0) {
    return `Herdr config was updated, but live reload failed: ${reload.stderr.trim() || reload.stdout.trim()}`;
  }
  return undefined;
}

export const herdrTarget: AppAdapter<HerdrAppConfig> = {
  name: 'herdr',
  label: 'Herdr',
  defaultConfig: { transparency: true },
  outputPath: herdrThemePath,
  generate: generateHerdr,
  detect: detectHerdr,
  currentTheme,
  activate: async () => {
    await writeTheme(generatedTheme());
    return reloadHerdr();
  },
  deactivate: async config => {
    await writeTheme(config.previousTheme ?? 'terminal');
    return reloadHerdr();
  },
};
