import type { ThemeLayer } from '../types.js';

const requiredColors = [
  'accent', 'panel_bg', 'surface0', 'active_space_bg', 'surface1', 'surface_dim',
  'separator', 'overlay0', 'overlay1', 'text', 'subtext0', 'mauve', 'green',
  'yellow', 'red', 'blue', 'teal', 'peach',
] as const;

function herdrColor(value: unknown, key: string): string {
  if (typeof value !== 'string') throw new Error(`Herdr color ${key} must resolve to a string`);
  return value.toUpperCase() === 'NONE' ? 'reset' : value;
}

export function generateHerdr(name: string, theme: ThemeLayer): string {
  const colors = theme.targets.herdr.colors;
  const lines = [
    '# Generated by one-theme. Edit the canonical theme JSON, not this file.',
    'schema_version = 1',
    `name = ${JSON.stringify(`ot-${name}`)}`,
    '',
    '[colors]',
  ];
  for (const key of requiredColors) {
    lines.push(`${key} = ${JSON.stringify(herdrColor(colors[key], key))}`);
  }
  lines.push('');
  return lines.join('\n');
}
