import { nvimThemePath } from '../paths.js';
import type { TargetAdapter } from '../targets.js';
import type { JsonValue, ThemeLayer } from '../types.js';

function lua(value: JsonValue): string {
  if (value === null) return 'nil';
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `{ ${value.map(lua).join(', ')} }`;
  return `{ ${Object.entries(value).map(([key, item]) => `[${JSON.stringify(key)}] = ${lua(item)}`).join(', ')} }`;
}

export function generateNeovim(name: string, theme: ThemeLayer): string {
  const lines = [
    '-- Generated by one-theme. Edit the canonical theme JSON, not this file.',
    `-- Theme: ot-${name}`,
    '',
    'if vim.g.colors_name then vim.cmd("highlight clear") end',
    'vim.o.termguicolors = true',
    `vim.g.colors_name = ${JSON.stringify(`ot-${name}`)}`,
    '',
  ];
  for (const [group, attributes] of Object.entries(theme.targets.neovim.highlights).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`vim.api.nvim_set_hl(0, ${JSON.stringify(group)}, ${lua(attributes)})`);
  }
  lines.push('');
  for (const [index, color] of Object.entries(theme.targets.neovim.terminalColors).sort(([a], [b]) => Number(a) - Number(b))) {
    lines.push(`vim.g.terminal_color_${index} = ${JSON.stringify(color)}`);
  }
  lines.push('');
  return lines.join('\n');
}

export const neovimTarget: TargetAdapter = {
  name: 'neovim',
  outputPath: nvimThemePath,
  generate: generateNeovim,
  activationHint: name => `activate Neovim manually with: :colorscheme ot-${name}`,
};
